github:
  client:
    id: Iv1.1417ff976c0c76e4
    secret: c03a0687c8117773752b2b6a23f7a9a03a767d5c
    redirectUri: http://localhost:8080/loginForGit


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_pro?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 129921
    driver-class-name: com.mysql.cj.jdbc.Driver

#  flyway: #配置flyway相关参数
#    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
#    enabled: true
#    # 如果数据库不是空表，需要设置成 true，否则启动报错
#    baseline-on-migrate: true
#    # 验证错误时 是否自动清除数据库 高危操作!
#    clean-on-validation-error: false
#    #sql文件存放位置
#    locations: classpath:db/migration

mybatis-plus:
  type-aliases-package: com.lin.communityproject.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


